{
    'name': 'Job Card Management',
    'version': '1.0',
    'category': 'Services',
    'depends': ['sale', 'purchase', 'purchase_requisition', 'stock', 'account', 'hr', 'hr_expense', 'mail'],
    'data': [
        'security/job_card_groups.xml',
        'security/ir.model.access.csv',
        'reports/job_card_report.xml',
        'views/technician_views.xml',
        'views/customer_views.xml',
        'views/vehicle_views.xml',
        'views/estimate_views.xml',
        'views/job_card_views.xml',
        'views/procurement_views.xml',
        'views/job_card_profitability_views.xml',
        'views/menu_views.xml',
    ],
    'installable': True,
    'application': True,
    'post_init_hook': 'create_access_rights',
}