{
    'name': 'Job Card Management',
    'version': '19.0.2.0.2',
    'category': 'Services',
    'author': 'Odoo Development Team',
    'license': 'LGPL-3',
    'depends': ['sale', 'sale_management', 'purchase', 'purchase_requisition', 'stock', 'account', 'hr', 'hr_expense', 'mail', 'havano_all_in_one'],
    'data': [
        'static/security/job_card_groups.xml',
        'static/security/ir.model.access.csv',
        'data/vehicle_catalog_seed.xml',
        'data/vehicle_records_seed.xml',
        'static/security/job_card_dashboard_access.xml',
        'reports/job_card_report.xml',
        'views/menu_root_views.xml',
        'views/technician_views.xml',
        'views/customer_views.xml',
        'views/vehicle_views.xml',
        'views/estimate_views.xml',
        'views/job_card_views.xml',
        'views/job_card_portal_templates.xml', 
        'views/procurement_views.xml',
        'views/purchase_views.xml',
        'views/job_card_profitability_views.xml',
        'views/menu_views.xml',
        'views/job_card_dashboard_views.xml',
        'views/estimate_portal_templates.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'job_card_management/static/src/scss/job_card_dashboard.scss',
            'job_card_management/static/src/js/job_card_dashboard.js',
            'job_card_management/static/src/xml/job_card_dashboard.xml',
            'job_card_management/static/src/scss/report_preview.scss',
        ],
        'web.assets_frontend_lazy': [
            'job_card_management/static/src/js/sale_update_line_button_guard.js',
        ],
    
    },
    'installable': True,
    'application': True,
    'post_init_hook': 'create_access_rights',
}