from . import backend_navigation
from . import customer
from . import vehicle_catalog
from . import res_config_settings
from . import vehicle
from . import estimate
from . import job_card
from . import procurement
from . import technician
from . import job_card_profitability
from . import job_card_dashboard